"""Create Executable: package a student's script into a standalone program.

This module is the whole "Create Executable" feature.  The editor's File menu
calls ``ExeBuilder``, which confirms with the student, shows a progress dialog
with a Cancel button, and reports the result.  The build itself is
``build_user_executable``, which runs on a worker thread and never touches Tk.

The build is deliberately separate from ``PEM/build.py`` -- that script builds
the PEM *application*; this one builds the *student's* program -- but it borrows
the same recipe for the hard case (bundle PySide6, the audio backend, and every
PythonMusic module; trim the large unused parts) from ``pem.builder.packages``.

Create Executable is offered only when PEM runs on a regular Python
installation (pip-installed, or from source).  The frozen PEM app leaves it out:
PyInstaller can't build from inside it, because the app's Python modules are
compiled into it rather than stored as files.

Two shapes of build, decided by whether the program uses PythonMusic:

* **Plain Python program.**  PyInstaller freezes the student's script directly,
  following and bundling exactly the imports it uses -- a small executable.  The
  program simply runs and exits like normal.

* **PythonMusic program.**  These need the whole PythonMusic stack (PySide6, the
  audio backend, every PythonMusic module), which those modules reach for
  dynamically in ways PyInstaller can't see -- so we force it all in, exactly as
  ``PEM/build.py`` does for the app.  The frozen entry point is a small
  *launcher* that:
    1. warms up the audio engine (if the program plays sound) so the first
       notes don't crackle;
    2. runs the student's *unmodified* script via ``runpy`` (so error messages
       still point at the student's real line numbers); and
    3. keeps the program alive afterwards -- a window program stays open until
       the person closes/quits it, and music plays to the end -- mirroring how
       PEM keeps a script running (see ``pem.execution.run.pump_gui_events``).

PyInstaller always runs as a child process so the student's "Cancel" button can
actually stop it.

Troubleshooting a build
-----------------------
When a build fails, a full record of it is saved to ``create-executable.log`` in
PythonMusic's log folder (on macOS, ``~/Library/Logs/PythonMusic``), and the
error message shows the file's path.  The record covers the settings used, which
Python ran the build, the folders searched for modules, where the audio library
and soundfont were found, the generated
``.spec`` file, the exact PyInstaller command, and PyInstaller's own output.
The log from the build before that is kept as ``create-executable.log.prev``.
A successful build leaves no log behind.

For development, set the ``PEM_BUILD_DEBUG`` environment variable before
launching PEM:

    PEM_BUILD_DEBUG=1 pem              # pip-installed PEM
    PEM_BUILD_DEBUG=1 python -m pem    # PEM run from source

With it set, every build saves its log (not just failed ones), each step is also
printed to the terminal, PyInstaller runs with its most detailed logging, and
the temporary work folder -- holding the generated ``.spec`` file and launcher --
is kept instead of deleted (its location is in the log).
"""

import os
import sys
import shlex
import shutil
import platform
import subprocess
import tempfile
import threading
import time
import traceback
from pathlib import Path
from tkinter import messagebox
from tkinter import Toplevel, StringVar
from tkinter.ttk import Progressbar, Label, Button, Frame

from pem.config import pemConf
from pem.builder import packages


# Set the PEM_BUILD_DEBUG environment variable before launching PEM to get a
# fuller record of every build (see "Troubleshooting a build" above).
DEBUG = bool(os.environ.get("PEM_BUILD_DEBUG"))


# PythonMusic's own top-level modules.  If a student's program imports any of
# these, we switch to the "batteries included" launcher build (see above).
PYTHONMUSIC_MODULES = {
   "music", "gui", "midi", "osc", "timer", "utilities",
   "iannix", "markov", "zipf", "image",
}

# Third-party packages that ship with PythonMusic.  Force-included alongside the
# PythonMusic modules, to cover the pieces those modules load dynamically.
# These are import names, not pip names.
RUNTIME_DEPENDENCIES = [
   "tinysoundfont",   # software synthesizer used for audio playback
   "sounddevice",     # audio output
   "soundfile",       # audio file reading/writing
   "rtmidi",          # MIDI backend (pip name: python-rtmidi)
   "osc4py3",         # OSC networking
   "regex",           # richer regular expressions
]

# The launcher that becomes the frozen entry point for PythonMusic programs.
# The __PEM_* tokens are filled in by _write_launcher (plain text replacement,
# so the template can contain its own braces freely).
_LAUNCHER_TEMPLATE = '''\
"""Launcher generated by PEM's "Create Executable" feature.

Runs the bundled PythonMusic program, then keeps it alive the way PEM does:
music plays to the end, and a window program stays open until it is finished.
"""
import os
import sys
import runpy
import threading

# Build setting: quit once the last window closes?  Suits a typical window
# program; turned off for programs where a window closes while the program keeps
# running (e.g. MidiIn's device chooser).
_QUIT_ON_WINDOW_CLOSE = __PEM_QUIT_ON_CLOSE__

# How many program windows are currently open (only tracked when the setting is
# on).  Updated as windows open and close so we know when the last one is gone.
_open_windows = {"count": 0, "opened_any": False}
_open_windows_lock = threading.Lock()


def _bundled_script_path():
   """Locate the student's script inside the frozen bundle."""
   base = getattr(sys, "_MEIPASS", os.path.dirname(os.path.abspath(__file__)))
   return os.path.join(base, __PEM_SCRIPT_NAME__)


def _watch_windows_for_quit():
   """Track open windows so the program can quit once the last one closes.

   Wraps Display creation to count each window and register a close callback
   (via the handler's registerEvent, which reliably makes the renderer report
   closes -- both the close box and Display.close()).  Only called when the
   "quit on last window" setting is on.
   """
   try:
      import gui
   except Exception:
      return

   _original_init = gui.Display.__init__

   def _counting_init(self, *args, **kwargs):
      _original_init(self, *args, **kwargs)
      with _open_windows_lock:
         _open_windows["count"] += 1
         _open_windows["opened_any"] = True

      def _on_close():
         with _open_windows_lock:
            _open_windows["count"] -= 1

      try:
         gui._handler().registerEvent(self._objectId, "displayClose", _on_close)
      except Exception:
         pass

   gui.Display.__init__ = _counting_init


def _all_windows_closed():
   """True once at least one window has opened and all of them have closed."""
   with _open_windows_lock:
      return _open_windows["opened_any"] and _open_windows["count"] <= 0


def _warm_up_audio():
   """Prepare the audio engine so the program's first moment doesn't crackle.

   A frozen executable has a much busier startup than a normal Python run
   (it unpacks and loads everything from the bundle), which can starve the
   synthesizer's small default audio buffer for a moment -- heard as a burst of
   gritty sound at the start.  Give the synthesizer a larger, more forgiving
   buffer *before* it opens the audio stream, then let it settle.  This only
   happens in the built program, so PEM and plain ``python`` runs are unchanged.
   """
   try:
      import tinysoundfont
      _original_start = tinysoundfont.Synth.start

      # The synth applies each scheduled note at the next audio-buffer boundary,
      # so the buffer size doubles as the timing grid: too large and note starts
      # get audibly quantized ("swung").  Pick the smallest buffer that still
      # rides out the frozen app's busy startup -- a modest bump over the tiny
      # default (1024), not a big one.
      def _start_with_larger_buffer(self, buffer_size=2048, **kwargs):
         return _original_start(self, buffer_size=buffer_size, **kwargs)

      # music.py starts the synth with the default buffer size, so raising the
      # default here is enough -- no change to PythonMusic needed.
      tinysoundfont.Synth.start = _start_with_larger_buffer
   except Exception:
      pass

   try:
      import music        # noqa: F401  (starts the synth, now with a bigger buffer)
      import time
      # Let the frozen app finish its busy startup before the program plays, so
      # the modest buffer above is enough to avoid under-runs.
      time.sleep(1.0)
   except Exception:
      pass


def _keep_program_alive():
   """Block until the program is genuinely finished.

   Windows live in PythonMusic's separate renderer process, which owns the Qt
   event loop and the Dock icon; music finishes when its scheduled timers drain.
   """
   import time
   _timer = sys.modules.get("timer")
   _gui = sys.modules.get("gui")
   _handler = getattr(_gui, "_GUI_HANDLER", None) if _gui is not None else None
   _child = getattr(_handler, "childProcess", None) if _handler is not None else None

   def _music_playing():
      return bool(getattr(_timer, "_activeTimers", [])) if _timer is not None else False

   def _window_open():
      if _child is None:
         return False
      try:
         return _child.is_alive()
      except Exception:
         return False

   # A window program: the window (and its Dock icon) live in PythonMusic's
   # separate renderer process, which runs its own Qt event loop.  This process
   # only has to stay alive alongside it -- and must NOT start its own
   # QApplication, or the app would show a second Dock icon.
   #
   # By default we stay up until the person quits the app (the renderer process
   # ends), because some features keep running after a window closes.  When the
   # "quit on last window" setting is on, we instead stop once the program's last
   # window has closed and any music has finished.
   if _child is not None:
      try:
         while _window_open():
            if _QUIT_ON_WINDOW_CLOSE and _all_windows_closed() and not _music_playing():
               break
            time.sleep(0.1)
      except KeyboardInterrupt:
         pass
      return

   # A music-only (or non-visual) program: run a real Qt event loop so this
   # process stays responsive (its Dock icon settles instead of bouncing) and
   # stop once the scheduled notes have all played.
   try:
      from PySide6 import QtWidgets, QtCore
   except Exception:
      QtWidgets = None

   if QtWidgets is not None:
      app = QtWidgets.QApplication.instance() or QtWidgets.QApplication(sys.argv)
      started = time.time()

      def _check():
         # Brief grace so we don't stop before the program schedules its notes.
         if time.time() - started < 0.3:
            return
         if not _music_playing():
            app.quit()

      ticker = QtCore.QTimer()
      ticker.timeout.connect(_check)
      ticker.start(150)
      app.exec()
      return

   # Fallback if Qt somehow isn't available.
   try:
      time.sleep(0.2)
      while _music_playing():
         time.sleep(0.1)
   except KeyboardInterrupt:
      pass


def main():
   __PEM_WARM_UP__
   if _QUIT_ON_WINDOW_CLOSE:
      _watch_windows_for_quit()

   scriptPath = _bundled_script_path()
   scriptDir = os.path.dirname(scriptPath)
   if scriptDir and scriptDir not in sys.path:
      sys.path.insert(0, scriptDir)

   # Run the student's program as if launched directly (it is __main__, on its
   # own real file, so tracebacks read naturally).
   try:
      runpy.run_path(scriptPath, run_name="__main__")
   except SystemExit:
      return

   _keep_program_alive()


if __name__ == "__main__":
   # PythonMusic opens windows in a spawned child process; freeze_support routes
   # those children to their own work instead of re-running this launcher.
   import multiprocessing
   multiprocessing.freeze_support()
   main()
'''


# ── Editor front end ───────────────────────────────────────────────────────────

class ExeBuilder:
   """Drives one "Create Executable" run for a single editor window."""

   def __init__(self, editwin):
      """Store the editor window whose script we will build.

      Args:
         editwin: EditorWindow, providing io.filename / io.save() / get_saved()
            and top (the window used as the dialog's parent).
      """
      self.editwin = editwin
      self.scriptPath = None

   def create_executable(self):
      """Confirm, then build the current script into a standalone executable."""
      # Make sure there is a saved file on disk to build from.
      if not self._ensure_file_saved():
         return

      # Let the student back out before a multi-minute build starts.
      if not self._confirm_build():
         return

      # PyInstaller is a dependency of PEM, but a pip install could be missing
      # it; check before we promise anything.
      if not self._check_pyinstaller():
         return

      self._run_build()

   def _ensure_file_saved(self):
      """Ensure the current buffer is saved to a file, returning success.

      Prompts for a filename if the buffer was never saved, and auto-saves any
      unsaved edits so we build exactly what the student sees.
      """
      filename = self.editwin.io.filename

      # A brand-new, never-saved buffer: ask where to save it first.
      if not filename:
         self.editwin.io.save(None)
         filename = self.editwin.io.filename
         if not filename:
            # Student cancelled the save dialog.
            return False

      # Unsaved edits: write them out so the build matches the editor.
      if not self.editwin.get_saved():
         self.editwin.io.save(None)

      self.scriptPath = Path(filename).resolve()
      return True

   def _confirm_build(self):
      """Ask the student to confirm the build, returning their choice."""
      system = platform.system()
      if system == "Windows":
         resultDescription = f"{self.scriptPath.stem}.exe"
      elif system == "Darwin":
         resultDescription = f"{self.scriptPath.stem}.app (plus a .tar.gz to share)"
      else:
         resultDescription = self.scriptPath.stem

      message = (
         f"Create a standalone program from {self.scriptPath.name}?\n\n"
         f"This makes {resultDescription} in the same folder as your script, "
         f"which you can share with others on the same kind of computer.\n\n"
         f"Building can take a few minutes."
      )
      return messagebox.askyesno(
         title="Create Executable",
         message=message,
         parent=self.editwin.text,
      )

   def _check_pyinstaller(self):
      """Return True if PyInstaller can be imported, else explain how to get it."""
      try:
         import PyInstaller  # noqa: F401
         return True
      except ImportError:
         messagebox.showerror(
            title="PyInstaller Not Found",
            message=(
               "Creating an executable needs the PyInstaller package.\n\n"
               "Install it from a terminal with:\n\n"
               "    pip install pyinstaller"
            ),
            parent=self.editwin.text,
         )
         return False

   def _show_console_preference(self):
      """Return the student's "Show Console" choice for built executables."""
      return pemConf.GetOption(
         "main", "CreateExecutable", "console",
         type="bool", default=False, warn_on_default=False,
      )

   def _quit_on_window_close_preference(self):
      """Return the student's "Quit When Last Window Closes" choice."""
      return pemConf.GetOption(
         "main", "CreateExecutable", "quit-on-window-close",
         type="bool", default=True, warn_on_default=False,
      )

   def _run_build(self):
      """Run the build on a background thread, driving a modal progress dialog.

      The dialog stays responsive and offers Cancel; when the worker finishes we
      show a success or failure message.  Tk is single-threaded, so the worker
      never touches widgets directly -- it hands its result back and we poll for
      it from the Tk event loop.
      """
      console = self._show_console_preference()
      quitOnWindowClose = self._quit_on_window_close_preference()
      cancelEvent = threading.Event()
      progressDialog = ProgressDialog(self.editwin.top, on_cancel=cancelEvent.set)

      # Filled in by the worker thread; read by the Tk-side poller below.
      resultBox = []
      latestStatus = ["Preparing the build..."]

      def report(statusText):
         # Called from the worker thread -- just stash the text; the poller
         # copies it onto the widget on the Tk thread.
         latestStatus[0] = statusText

      def worker():
         try:
            result = build_user_executable(
               self.scriptPath,
               console=console,
               quit_on_window_close=quitOnWindowClose,
               progress=report,
               cancel_event=cancelEvent,
            )
         except Exception as error:
            result = BuildResult(
               False,
               message=f"The executable couldn't be built, and PEM couldn't save a build log.\n\n{error}",
            )
         resultBox.append(result)

      buildThread = threading.Thread(target=worker, daemon=True)
      buildThread.start()

      # Poll from the Tk event loop so the dialog keeps painting and the Cancel
      # button stays clickable while the worker runs.
      def poll():
         progressDialog.update_status(latestStatus[0])
         if resultBox:
            progressDialog.close()
            self._report_result(resultBox[0])
         else:
            self.editwin.top.after(100, poll)

      self.editwin.top.after(100, poll)

   def _report_result(self, result):
      """Show the outcome of a finished build to the student."""
      if result.cancelled:
         # Nothing to say -- the student asked us to stop.
         return

      if result.success:
         messagebox.showinfo(
            title="Executable Created",
            message=result.message,
            parent=self.editwin.text,
         )
      else:
         messagebox.showerror(
            title="Couldn't Create Executable",
            message=result.message,
            parent=self.editwin.text,
         )


class ProgressDialog:
   """A small modal dialog showing build progress, with a Cancel button."""

   def __init__(self, parent, on_cancel=None):
      """Build and show the dialog.

      Args:
         parent: The window to center on and block.
         on_cancel: Called (once) when the student clicks Cancel.
      """
      self.on_cancel = on_cancel
      self.cancelled = False

      self.dialog = Toplevel(parent)
      self.dialog.title("Creating Executable")
      self.dialog.resizable(False, False)

      # Modal: sit above the editor and take input until the build ends.
      self.dialog.transient(parent)
      self.dialog.grab_set()
      # Treat the window-close button the same as Cancel.
      self.dialog.protocol("WM_DELETE_WINDOW", self._cancel)

      body = Frame(self.dialog, padding=20)
      body.pack(fill="both", expand=True)

      self.statusVar = StringVar(master=self.dialog, value="Preparing the build...")
      Label(body, textvariable=self.statusVar, wraplength=340).pack(
         anchor="w", pady=(0, 10))

      self.progress = Progressbar(body, mode="indeterminate", length=340)
      self.progress.pack(fill="x")
      self.progress.start(12)

      self.cancelButton = Button(body, text="Cancel", command=self._cancel)
      self.cancelButton.pack(anchor="e", pady=(14, 0))

      self._center_on(parent)

   def _center_on(self, parent):
      """Position the dialog over the middle of its parent window."""
      self.dialog.update_idletasks()
      width = self.dialog.winfo_width()
      height = self.dialog.winfo_height()
      x = parent.winfo_x() + (parent.winfo_width() - width) // 2
      y = parent.winfo_y() + (parent.winfo_height() - height) // 2
      self.dialog.geometry(f"+{x}+{y}")

   def _cancel(self):
      """Handle a Cancel click (or window close): tell the build to stop, once."""
      if self.cancelled:
         return
      self.cancelled = True
      self.statusVar.set("Cancelling...")
      self.cancelButton.configure(state="disabled")
      if self.on_cancel is not None:
         self.on_cancel()

   def update_status(self, message):
      """Show a new status line (unless the student is cancelling)."""
      if not self.cancelled:
         self.statusVar.set(message)

   def close(self):
      """Stop the animation and dismiss the dialog."""
      try:
         self.progress.stop()
         self.dialog.grab_release()
         self.dialog.destroy()
      except Exception:
         pass


# ── The build ──────────────────────────────────────────────────────────────────

class BuildResult:
   """Outcome of a build attempt, returned to ExeBuilder for display.

   Attributes:
      success (bool): True if an executable was produced.
      output_path (Path or None): The finished executable / app / archive.
      message (str): A student-friendly explanation of the result.
      cancelled (bool): True if the student cancelled the build.
      log_path (Path or None): Where this build's log was saved, if it was saved.
   """

   def __init__(self, success, output_path=None, message="",
                cancelled=False, log_path=None):
      self.success = success
      self.output_path = output_path
      self.message = message
      self.cancelled = cancelled
      self.log_path = log_path


def build_user_executable(script_path, console=False, quit_on_window_close=False,
                          progress=None, cancel_event=None):
   """Build a standalone executable from ``script_path``.

   Args:
      script_path: Path to the student's ``.py`` file (already saved to disk).
      console (bool): Build a console executable (a terminal window is attached,
         so ``print()`` and ``input()`` work).  When False the program runs
         windowed, with no console -- fine for GUI/audio programs that never
         read typed input.  Comes from the "Show Console" preference.
      quit_on_window_close (bool): For a window program, end the program once its
         last window closes.  Off by default (some features keep running after a
         window closes).  Comes from the "Quit When Last Window Closes" preference.
      progress (callable or None): Called with a short status string as the
         build moves through its stages, for the progress dialog.
      cancel_event (threading.Event or None): If set mid-build, the PyInstaller
         child process is terminated and a cancelled result is returned.

   Returns:
      BuildResult.  A failed build's message says so and gives the path of its
      saved log (see "Troubleshooting a build" in the module docstring).
   """
   report = progress if progress is not None else (lambda message: None)
   log = _BuildLog()
   tempDir = None
   # The build counts as failed unless it finishes (or the student cancels it).
   result = BuildResult(False)

   try:
      scriptPath = Path(script_path).resolve()
      scriptDir = scriptPath.parent
      scriptName = scriptPath.stem

      # Everything transient (spec file, work folder, generated launcher) goes in
      # one temp dir, removed at the end unless PEM_BUILD_DEBUG is set.
      tempDir = Path(tempfile.mkdtemp(prefix="pem_build_"))
      _note_environment(log, scriptPath, console, quit_on_window_close, tempDir)

      report("Looking at your program...")
      usedModules = _imports_including_siblings(scriptPath, scriptDir) & PYTHONMUSIC_MODULES
      usesPythonMusic = bool(usedModules)
      playsAudio = "music" in usedModules
      usesWindows = "gui" in usedModules
      externalImports = _classify_imports(scriptPath, scriptDir)
      siblingModules = _find_local_modules(scriptPath, scriptDir)
      log.note(f"PythonMusic modules used: {sorted(usedModules) or 'none'}")
      log.note(f"other third-party imports: {externalImports or 'none'}")
      log.note(f"sibling files imported: {siblingModules or 'none'}")

      report("Preparing the build...")
      specPath = _write_spec(
         tempDir=tempDir,
         scriptPath=scriptPath,
         scriptName=scriptName,
         console=console,
         usesPythonMusic=usesPythonMusic,
         playsAudio=playsAudio,
         # The quit-on-close behaviour only matters for programs with windows.
         quitOnWindowClose=quit_on_window_close and usesWindows,
         siblingModules=siblingModules,
         externalImports=externalImports,
         log=log,
      )
      log.section("generated spec file", specPath.read_text(encoding="utf-8"))

      report("Building the executable (this can take a few minutes)...")
      # Build into the temp folder, not the student's folder: PyInstaller's
      # macOS build leaves an intermediate onedir folder next to the .app, and
      # we don't want that clutter landing beside the student's script.  We move
      # just the finished result out afterwards.
      built, buildLog = _run_pyinstaller(
         specPath=specPath,
         distDir=tempDir / "dist",
         workDir=tempDir / "build",
         log=log,
         cancel_event=cancel_event,
      )
      log.section("PyInstaller output", buildLog)

      if cancel_event is not None and cancel_event.is_set():
         log.note("the build was cancelled")
         result = BuildResult(False, cancelled=True)
      elif not built:
         log.note("PyInstaller did not finish successfully")
      else:
         report("Finishing up...")
         shareablePath, message = _collect_output(
            tempDir / "dist", scriptDir, scriptName)
         if shareablePath is None:
            log.note(f"PyInstaller finished, but no finished program was found in {tempDir / 'dist'}")
         else:
            log.note(f"finished program: {shareablePath}")
            result = BuildResult(True, output_path=shareablePath, message=message)

   except Exception:
      # An error in PEM's own build code -- record exactly where it happened.
      log.note("unexpected error while building")
      log.section("traceback", traceback.format_exc())

   finally:
      # The finished executable lives in the student's folder, not here, so the
      # whole temp tree is safe to remove.  In debug mode it is kept so the
      # generated spec file and launcher can be inspected.
      if tempDir is not None:
         if DEBUG:
            log.note(f"kept the temporary work folder: {tempDir}")
         else:
            shutil.rmtree(tempDir, ignore_errors=True)

   # A failed build always saves its log (every build does in debug mode), and
   # its message points to the log for the details.
   buildFailed = not result.success and not result.cancelled
   if buildFailed or DEBUG:
      result.log_path = log.save()
   if buildFailed:
      if result.log_path is None:
         result.message = "The executable couldn't be built, and PEM couldn't save a build log."
      else:
         result.message = f"The executable couldn't be built.\n\nDetails are in the build log:\n{result.log_path}"
   return result


# ── Build log ──────────────────────────────────────────────────────────────────

class _BuildLog:
   """Records one build so a failure can be diagnosed after the fact.

   Lines are collected in memory while the build runs; save() writes them to the
   log file once the build is over.
   """

   def __init__(self):
      self.lines = []
      self.startTime = time.perf_counter()

   def note(self, text):
      """Record one step of the build, with the seconds elapsed so far.

      In debug mode the line is also printed to the terminal, when there is one
      (a windowed app launched from Finder has none).
      """
      elapsedSeconds = time.perf_counter() - self.startTime
      line = f"[{elapsedSeconds:7.1f}s] {text}"
      self.lines.append(line)
      if DEBUG:
         stream = sys.__stderr__ or sys.stderr
         if stream is not None:
            try:
               stream.write(line + "\n")
               stream.flush()
            except Exception:
               pass

   def section(self, title, body):
      """Record a block of text, such as the generated spec or PyInstaller's output."""
      self.lines.append(f"----- {title} -----")
      self.lines.append(body.rstrip("\n"))
      self.lines.append(f"----- end of {title} -----")

   def save(self):
      """Write the log file, keeping the previous build's log as ``.prev``.

      Returns the log file's path, or None if it couldn't be written.
      """
      logPath = _build_log_path()
      previousPath = logPath.with_suffix(logPath.suffix + ".prev")
      try:
         if logPath.exists():
            if previousPath.exists():
               previousPath.unlink()
            logPath.rename(previousPath)
         logPath.write_text("\n".join(self.lines) + "\n", encoding="utf-8")
         return logPath
      except OSError:
         return None


def _build_log_path():
   """Return the build log's path, creating its folder if needed.

   Uses the same per-platform folder as PythonMusic's GUI renderer log.
   """
   if sys.platform == "darwin":
      base = Path.home() / "Library" / "Logs" / "PythonMusic"
   elif sys.platform == "win32":
      base = Path(os.environ.get("LOCALAPPDATA", str(Path.home()))) / "PythonMusic" / "Logs"
   else:
      stateHome = os.environ.get("XDG_STATE_HOME") or str(Path.home() / ".local" / "state")
      base = Path(stateHome) / "PythonMusic" / "logs"
   try:
      base.mkdir(parents=True, exist_ok=True)
   except OSError:
      pass
   return base / "create-executable.log"


def _note_environment(log, scriptPath, console, quitOnWindowClose, tempDir):
   """Record the settings and surroundings of this build.

   Many build problems come down to *where* things are: which Python is running
   the build, and which folders are searched for modules.
   """
   log.note(f"Create Executable for: {scriptPath}")
   log.note(f"settings: console={console}, quit_on_window_close={quitOnWindowClose}, debug={DEBUG}")
   log.note(f"platform: {platform.platform()}, Python {platform.python_version()}")
   log.note(f"sys.executable: {sys.executable}")
   log.note(f"working folder: {os.getcwd()}")
   log.note(f"temporary work folder: {tempDir}")
   log.note("module search path (sys.path):")
   for entry in sys.path:
      missing = "" if os.path.exists(entry) else "   (missing)"
      log.note(f"    {entry}{missing}")


# ── Import analysis ────────────────────────────────────────────────────────────

def _script_imports(scriptPath):
   """Return the set of top-level module names imported by one script.

   Uses the AST so it understands ``import a.b`` and ``from a import b``.
   Returns an empty set if the file can't be read or parsed -- import analysis
   is advisory, so a parse failure must never block a build.
   """
   import ast

   names = set()
   try:
      source = Path(scriptPath).read_text(encoding="utf-8")
      tree = ast.parse(source)
   except Exception:
      return names

   for node in ast.walk(tree):
      if isinstance(node, ast.Import):
         for alias in node.names:
            names.add(alias.name.split(".")[0])
      elif isinstance(node, ast.ImportFrom):
         if node.module and node.level == 0:
            names.add(node.module.split(".")[0])
   return names


def _imports_including_siblings(scriptPath, scriptDir):
   """Return imports of the script *and* of any sibling files it imports.

   A student may ``import music`` from a helper file rather than their main
   script, so we look one level into sibling modules too before deciding whether
   the program uses PythonMusic.
   """
   allImports = set(_script_imports(scriptPath))
   for name in list(allImports):
      sibling = scriptDir / f"{name}.py"
      if sibling.exists() and sibling != scriptPath:
         allImports |= _script_imports(sibling)
      package_init = scriptDir / name / "__init__.py"
      if package_init.exists():
         allImports |= _script_imports(package_init)
   return allImports


def _classify_imports(scriptPath, scriptDir):
   """Return third-party imports that are neither PythonMusic nor a sibling file.

   If a build fails, these are the most likely culprit, so we surface them in
   the failure message.
   """
   bundled = set(PYTHONMUSIC_MODULES) | set(RUNTIME_DEPENDENCIES)
   for name in packages.CORE_LIBRARIES:
      bundled.add(name.split(".")[0])
   stdlib = set(sys.stdlib_module_names)

   external = []
   for name in sorted(_script_imports(scriptPath)):
      if name in bundled or name in stdlib:
         continue
      if (scriptDir / f"{name}.py").exists():
         continue
      if (scriptDir / name / "__init__.py").exists():
         continue
      external.append(name)
   return external


def _find_local_modules(scriptPath, scriptDir):
   """Find sibling ``.py`` files / packages the script imports, to bundle them.

   Returns a list of ``(name, is_package)`` tuples.  A student might split a
   project across a few files that sit next to the script; those must ride along
   in the executable.
   """
   siblings = []
   for name in _script_imports(scriptPath):
      package = scriptDir / name
      if package.is_dir() and (package / "__init__.py").exists():
         siblings.append((name, True))
         continue
      module = scriptDir / f"{name}.py"
      if module.exists() and module != scriptPath:
         siblings.append((name, False))
   return siblings


# ── Launcher for PythonMusic programs ──────────────────────────────────────────

def _write_launcher(tempDir, scriptName, playsAudio, quitOnWindowClose):
   """Write the launcher that becomes the frozen entry point, and return its path.

   ``scriptName`` is the student's filename (e.g. ``furElise.py``); the launcher
   finds it in the bundle and runs it.  ``playsAudio`` decides whether to warm up
   the audio engine first; ``quitOnWindowClose`` decides whether the program ends
   when its last window closes.
   """
   warmUpCall = "_warm_up_audio()" if playsAudio else "pass"
   content = (
      _LAUNCHER_TEMPLATE
      .replace("__PEM_SCRIPT_NAME__", repr(scriptName))
      .replace("__PEM_WARM_UP__", warmUpCall)
      .replace("__PEM_QUIT_ON_CLOSE__", "True" if quitOnWindowClose else "False")
   )
   launcherPath = tempDir / "_pem_launcher.py"
   launcherPath.write_text(content, encoding="utf-8")
   return launcherPath


# ── Spec generation (mirrors PEM/build.py's recipe, for a user script) ─────────

def _locate_libportaudio():
   """Return the bundled PortAudio library path, if this platform ships one.

   PythonMusic bundles ``libportaudio`` (macOS) so audio output works without a
   system install; ``PEM/build.py`` bundles it for the app the same way.  In a
   pip install it lives inside the installed ``PythonMusic`` package.
   """
   try:
      import PythonMusic
   except Exception:
      return None
   binDir = Path(PythonMusic.__file__).parent / "bin"
   for candidate in ("libportaudio.2.dylib",):
      libPath = binDir / candidate
      if libPath.exists():
         return libPath
   return None


def _locate_soundfont():
   """Return a soundfont (.sf2) file to bundle, or None if none is found.

   Mirrors how ``music.py``'s ``_findSoundfont`` searches at runtime, so we
   bundle the same soundfont the student already uses.  Bundling it means a
   program that plays MIDI still has sound on a computer that has never run
   PythonMusic -- otherwise ``music.py`` falls back to *prompting* for a
   download, which a windowed executable (no console) can't answer.
   """
   candidates = []

   fromEnv = os.getenv("CREATIVEPYTHON_SOUNDFONT")
   if fromEnv:
      candidates.append(Path(fromEnv))

   home = Path.home()
   candidates += [home / "Soundfonts", home / "soundfonts"]

   # The usual location: PythonMusic's download cache.
   try:
      from platformdirs import user_data_dir
      candidates.append(Path(user_data_dir("PythonMusic", "CofC")) / "Soundfonts")
   except Exception:
      pass

   for candidate in candidates:
      try:
         if candidate.is_file() and candidate.suffix.lower() == ".sf2":
            return candidate
         if candidate.is_dir():
            found = list(candidate.glob("*.sf2")) + list(candidate.glob("*.SF2"))
            if found:
               return found[0]
      except Exception:
         pass
   return None


def _write_spec(tempDir, scriptPath, scriptName, console, usesPythonMusic,
                playsAudio, quitOnWindowClose, siblingModules, externalImports, log):
   """Write a PyInstaller ``.spec`` for the student's program and return its path.

   For a PythonMusic program the entry point is the generated launcher, the
   student's script rides along as data (the launcher runs it), and the whole
   PythonMusic stack plus the audio library are forced in.  For a plain program
   PyInstaller freezes the student's script directly and follows its own
   imports.  Either way the large unused parts are excluded (see
   ``packages.getExcludes``), and the executable shape is chosen per platform:
   a ``.app`` on macOS, a single file elsewhere.  Where each bundled resource
   was found is recorded in ``log``.
   """
   scriptDir = scriptPath.parent
   excludes = packages.getExcludes(profile="user_script")

   if usesPythonMusic:
      entryPath = _write_launcher(tempDir, scriptPath.name, playsAudio,
                                  quitOnWindowClose)
      log.note(f"entry point: generated launcher {entryPath}")
      # The launcher runs the student's script from the bundle, so the script
      # travels as data rather than as an analysed entry point.
      datas = [(str(scriptPath), ".")]
      # Force in everything PythonMusic reaches for dynamically, the sibling
      # files this program imports, and any third-party packages it uses.
      hiddenimports = list(packages.CORE_LIBRARIES) + list(RUNTIME_DEPENDENCIES)
      hiddenimports += [name for name, _isPackage in siblingModules]
      hiddenimports += externalImports
      binaries = []
      libportaudio = _locate_libportaudio()
      log.note(f"PortAudio library: {libportaudio or 'not found'}")
      if libportaudio is not None:
         binaries.append((str(libportaudio), "."))

      # Bundle the soundfont so MIDI programs have sound on any computer, not
      # just one that has already downloaded it.  music.py looks for it under
      # "soundfonts" in the bundle (its _MEIPASS/soundfonts candidate).
      if playsAudio:
         soundfont = _locate_soundfont()
         log.note(f"soundfont: {soundfont or 'not found'}")
         if soundfont is not None:
            datas.append((str(soundfont), "soundfonts"))
   else:
      # Plain program: freeze the script itself and let PyInstaller follow its
      # imports.
      entryPath = scriptPath
      log.note(f"entry point: the script itself ({entryPath})")
      datas = []
      hiddenimports = []
      binaries = []

   system = platform.system()
   if system == "Darwin":
      if console:
         # A console program on macOS: a .app bundle can't show a console when
         # double-clicked (Finder attaches no terminal).  Build a single
         # executable named ".command" instead -- macOS opens .command files in
         # Terminal on double-click, so print()/input() and the console appear.
         exeText = _ONEFILE_EXE_TEMPLATE.format(name=scriptName + ".command", console=True)
      else:
         exeText = _MACOS_EXE_TEMPLATE.format(name=scriptName, console=False)
   else:
      exeText = _ONEFILE_EXE_TEMPLATE.format(name=scriptName, console=console)

   specText = _SPEC_TEMPLATE.format(
      entry=repr(str(entryPath)),
      pathex=repr([str(scriptDir)]),
      binaries=repr(binaries),
      datas=repr(datas),
      hiddenimports=repr(hiddenimports),
      excludes=repr(excludes),
      exe_text=exeText,
   )

   specPath = tempDir / f"{scriptName}.spec"
   specPath.write_text(specText, encoding="utf-8")
   return specPath


_SPEC_TEMPLATE = """\
# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by PEM's "Create Executable" feature.
a = Analysis(
   [{entry}],
   pathex={pathex},
   binaries={binaries},
   datas={datas},
   hiddenimports={hiddenimports},
   hookspath=[],
   hooksconfig={{}},
   runtime_hooks=[],
   excludes={excludes},
   noarchive=False,
   optimize=0,
)
pyz = PYZ(a.pure, a.zipped_data)
{exe_text}
"""

_ONEFILE_EXE_TEMPLATE = """\
exe = EXE(
   pyz,
   a.scripts,
   a.binaries,
   a.zipfiles,
   a.datas,
   [],
   exclude_binaries=False,
   name={name!r},
   debug=False,
   bootloader_ignore_signals=False,
   strip=False,
   upx=True,
   upx_exclude=[],
   onefile=True,
   console={console},
   disable_windowed_traceback=False,
   icon=None,
   manifest=None,
)
"""

_MACOS_EXE_TEMPLATE = """\
exe = EXE(
   pyz,
   a.scripts,
   [],
   exclude_binaries=True,
   name={name!r},
   debug=False,
   bootloader_ignore_signals=False,
   strip=False,
   upx=True,
   upx_exclude=[],
   console={console},
   disable_windowed_traceback=False,
   argv_emulation=False,
   target_arch=None,
   codesign_identity=None,
   entitlements_file=None,
   icon=None,
)
coll = COLLECT(
   exe,
   a.binaries,
   a.zipfiles,
   a.datas,
   strip=False,
   upx=True,
   upx_exclude=[],
   name={name!r},
)
app = BUNDLE(
   coll,
   name={name!r} + '.app',
   icon=None,
   bundle_identifier=None,
)
"""


# ── Running PyInstaller as a cancellable child process ─────────────────────────

def _pyinstaller_command(specPath, distDir, workDir):
   """Build the command that runs PyInstaller on ``specPath``.

   Uses the current interpreter's PyInstaller (``-m PyInstaller``), so
   ``sys.executable`` must be a regular Python interpreter -- one reason the
   frozen PEM app doesn't offer Create Executable.
   """
   command = [
      sys.executable, "-m", "PyInstaller",
      str(specPath),
      "--distpath", str(distDir),
      "--workpath", str(workDir),
      "--noconfirm",
      "--clean",
   ]
   if DEBUG:
      # PyInstaller's most detailed output, showing why it made each choice.
      command += ["--log-level", "DEBUG"]
   return command


def _run_pyinstaller(specPath, distDir, workDir, log, cancel_event=None):
   """Run PyInstaller as a child process, watching for cancellation.

   Returns ``(success, output)`` where ``output`` is PyInstaller's combined
   output (used to explain failures).  If ``cancel_event`` is set while the
   build runs, the child process is terminated and ``success`` is False.  The
   command and its exit code are recorded in ``log``.
   """
   command = _pyinstaller_command(specPath, distDir, workDir)
   log.note("running: " + shlex.join(command))

   process = subprocess.Popen(
      command,
      stdout=subprocess.PIPE,
      stderr=subprocess.STDOUT,
      text=True,
   )

   outputLines = []
   # Drain output line by line so a cancel request is noticed promptly rather
   # than only after the (multi-minute) build finishes.
   while True:
      if cancel_event is not None and cancel_event.is_set():
         log.note("stopping PyInstaller because the build was cancelled")
         _terminate(process)
         return False, "".join(outputLines)
      line = process.stdout.readline()
      if line:
         outputLines.append(line)
         continue
      if process.poll() is not None:
         break

   returnCode = process.wait()
   log.note(f"PyInstaller exited with code {returnCode}")
   return returnCode == 0, "".join(outputLines)


def _terminate(process):
   """Stop a running PyInstaller child process, escalating if it lingers."""
   try:
      process.terminate()
      try:
         process.wait(timeout=5)
      except subprocess.TimeoutExpired:
         process.kill()
   except Exception:
      pass


# ── Locating and packaging the result ──────────────────────────────────────────

def _collect_output(distDir, scriptDir, scriptName):
   """Move the finished program into the student's folder.

   Returns ``(shareable_path, message)`` describing what was produced, or
   ``(None, "")`` if nothing was built.  On macOS this leaves the runnable
   ``.app`` plus a ``.tar.gz`` to share (a plain ``.zip`` loses the executable
   permissions and symlinks a Mac app needs, so the app would be broken -- the
   same reason ``PEM/build.py`` distributes a tar.gz).  On Windows/Linux it
   leaves the single executable file.
   """
   system = platform.system()

   if system == "Darwin":
      # A windowed program builds a .app; a console program builds a .command
      # single-file executable (opens in Terminal on double-click).
      builtApp = distDir / f"{scriptName}.app"
      builtCommand = distDir / f"{scriptName}.command"

      if builtApp.exists():
         appPath = scriptDir / f"{scriptName}.app"
         _replace_path(appPath, builtApp)
         _adhoc_codesign(appPath)
         archivePath = _make_tar_gz(scriptDir, f"{scriptName}.app",
                                    scriptDir / f"{scriptName}.tar.gz")
         message = (
            "Your program is ready.\n\n"
            f"To run it now:  {appPath.name}\n"
            f"To share it:    {archivePath.name if archivePath else appPath.name}\n\n"
            "Others can unpack the .tar.gz and run the app -- sharing it this way "
            "keeps the app working on their Mac."
         )
         return (archivePath or appPath), message

      if builtCommand.exists():
         commandPath = scriptDir / f"{scriptName}.command"
         _replace_path(commandPath, builtCommand)
         # Make sure it stays runnable (double-click in Finder needs the
         # executable bit; tar.gz below preserves it for sharing).
         try:
            commandPath.chmod(commandPath.stat().st_mode | 0o111)
         except Exception:
            pass
         archivePath = _make_tar_gz(scriptDir, commandPath.name,
                                    scriptDir / f"{scriptName}.tar.gz")
         message = (
            "Your program is ready.\n\n"
            f"To run it now:  double-click {commandPath.name} (it opens in Terminal)\n"
            f"To share it:    {archivePath.name if archivePath else commandPath.name}\n\n"
            "The Terminal window is where the program prints and reads typed input."
         )
         return (archivePath or commandPath), message

      return None, ""

   # Windows / Linux: a single executable file, already shareable as-is.
   builtExe = distDir / (f"{scriptName}.exe" if system == "Windows" else scriptName)
   if not builtExe.exists():
      return None, ""
   exePath = scriptDir / builtExe.name
   _replace_path(exePath, builtExe)
   message = (
      "Your program is ready.\n\n"
      f"{exePath}\n\n"
      "You can share this file with others using the same kind of computer."
   )
   return exePath, message


def _replace_path(destination, source):
   """Move ``source`` to ``destination``, replacing anything already there."""
   if destination.exists():
      if destination.is_dir():
         shutil.rmtree(destination, ignore_errors=True)
      else:
         destination.unlink()
   shutil.move(str(source), str(destination))


def _adhoc_codesign(appPath):
   """Ad-hoc sign a macOS ``.app`` to reduce Gatekeeper friction when shared.

   This is the same step ``PEM/build.py`` does; it avoids the "app is damaged"
   error.  Best-effort: a signing failure must not fail the whole build.
   """
   try:
      subprocess.run(
         ["codesign", "--deep", "--force", "--sign", "-", str(appPath)],
         stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=False,
      )
   except Exception:
      pass


def _make_tar_gz(sourceDir, memberName, archivePath):
   """Create ``archivePath`` as a gzip tar of ``memberName`` inside ``sourceDir``.

   Uses ``tar`` (like ``PEM/build.py``) so the app's executable permissions and
   internal symlinks survive -- a plain zip does not preserve these, which is
   what left the shared app broken.  Returns the archive path, or None on
   failure (the student still has the runnable ``.app``).
   """
   try:
      if archivePath.exists():
         archivePath.unlink()
      subprocess.run(
         ["tar", "-czf", str(archivePath), "-C", str(sourceDir), memberName],
         check=True,
      )
      return archivePath
   except Exception:
      return None
